### ISSUE TITLE
Pointers to section bodies not updated in pre-existing section headers when new .sbom section header added

### ISSUE THREAD

**Issue by MatchPoint** [hughsie/python-uswid#14]
Addition of section contains two actions – adding the header and the body. Due to PE/COFF format all section headers come first, before all the bodies. So each section has a pointer to start of the body in the same file. When adding new section header all bodies are getting pushed down in the file by the size of section header. However pointers to bodies in existing sections are not updated to reflect this change. When this happens, down the road during the creation of firmware volume from stand alone .ffs files copy is happening based on information stored in section headers, which leads to corruption of file content.

**Comment by MatchPoint** [comment]
versions used:
uswid                        0.2.0
pefile                       2021.9.3

**Comment by hughsie** [comment]
Agree; the pefile hack turns out to be just that, a hack. I've removed the code that adds the section to avoid corrupting files. In the meantime there are three options:

 * Add the .sbom section (of any size) during compile and allow uswid to modify it (it's going to be aligned to file alignment, which is fine for the small coSWID blob)
 * Use objcopy (e.g. from WSL) to modify the pefile to add the section and relink the file
 * Use the experimental wip/hughsie/pefile-mine-mine branch that does the linker thing.
